repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      # Check for merge conflict.
      - id: check-merge-conflict
        stages: [ commit, push ]
      # Check if files parse as valid python.
      - id: check-ast
        stages: [ commit ]
    
  # local hooks
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry
        args:
          - run
          - black
        language: system
        types: [ python ]
        stages: [ commit ]
        # Black should use the config from the pyproject.toml file

      - id: isort
        name: isort
        entry: poetry
        args:
          - run
          - isort
          - --profile
          - black
        language: system
        types: [ python ]
        stages: [ commit ]
        # isort's config is also stored in pyproject.toml

      - id: flake8
        name: flake8
        entry: poetry
        args:
          - run
          - flake8
        language: system
        always_run: true
        pass_filenames: false
        stages: [ push ]
