name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'You just opened an issue! Please remind the maintainers of the project to update this so they can greet others with a helping issue message!'
        pr-message: 'You just opened a pull request! Please remind the maintainers of the project to update this so they can greet others with a helping pull request message!'
